INSERT INTO products (slug, name, type, description, image_url) VALUES
('dsa-alley-cat', 'DSA / Alley Cat', 'merch', 'Physical release of DSA / Alley Cat on cassette and black vinyl.', '/images/DSA-AC-Vinyl.webp'),
('angel-shirt', 'Angel Shirt', 'merch', 'White Angel shirt available with black or green text in sizes S through XXL.', '/images/AngelsBlackText-store.png'),
('what-lies-ahead-of-me', 'What Lies Ahead of Me', 'merch', 'What Lies Ahead of Me available on CD and 12" vinyl variants.', '/images/WLAOMBlackVinyl.webp'),
('collider', 'Collider', 'merch', 'Collider on 12" black vinyl.', '/images/ColliderBlackVinyl.webp'),
('auh-cleveland-2026-05-03', 'Cleveland (May 3, 2026)', 'ticket', 'General admission', ''),
('auh-nashville-2026-05-05', 'Nashville (May 5, 2026)', 'ticket', 'General admission', ''),
('auh-atlanta-2026-05-07', 'Atlanta (May 7, 2026)', 'ticket', 'General admission', ''),
('auh-asheville-2026-05-09', 'Asheville (May 9, 2026)', 'ticket', 'General admission', ''),
('auh-carrboro-2026-05-10', 'Carrboro (May 10, 2026)', 'ticket', 'General admission', ''),
('auh-nyc-2026-05-12', 'NYC (May 12, 2026)', 'ticket', 'General admission', ''),
('auh-cambridge-2026-05-13', 'Cambridge (May 13, 2026)', 'ticket', 'General admission', ''),
('auh-hamden-2026-05-14', 'Hamden (May 14, 2026)', 'ticket', 'General admission', ''),
('auh-washington-dc-2026-05-15', 'Washington, DC (May 15, 2026)', 'ticket', 'General admission', ''),
('auh-allentown-2026-05-16', 'Allentown (May 16, 2026)', 'ticket', 'General admission', ''),
('auh-philadelphia-2026-05-17', 'Philadelphia (May 17, 2026)', 'ticket', 'General admission', ''),
('auh-detroit-2026-05-19', 'Detroit (May 19, 2026)', 'ticket', 'General admission', ''),
('auh-toronto-2026-05-20', 'Toronto (May 20, 2026)', 'ticket', 'General admission', '');

INSERT INTO product_variants (product_id, name, price_cents, stock_qty) VALUES
((SELECT id FROM products WHERE slug = 'dsa-alley-cat'), 'Cassette', 1200, 25),
((SELECT id FROM products WHERE slug = 'dsa-alley-cat'), 'Black Vinyl', 2200, 20),
((SELECT id FROM products WHERE slug = 'angel-shirt'), 'Black Text / S', 3000, 12),
((SELECT id FROM products WHERE slug = 'angel-shirt'), 'Black Text / M', 3000, 12),
((SELECT id FROM products WHERE slug = 'angel-shirt'), 'Black Text / L', 3000, 12),
((SELECT id FROM products WHERE slug = 'angel-shirt'), 'Black Text / XL', 3000, 10),
((SELECT id FROM products WHERE slug = 'angel-shirt'), 'Black Text / XXL', 3000, 8),
((SELECT id FROM products WHERE slug = 'angel-shirt'), 'Green Text / S', 3000, 12),
((SELECT id FROM products WHERE slug = 'angel-shirt'), 'Green Text / M', 3000, 12),
((SELECT id FROM products WHERE slug = 'angel-shirt'), 'Green Text / L', 3000, 12),
((SELECT id FROM products WHERE slug = 'angel-shirt'), 'Green Text / XL', 3000, 10),
((SELECT id FROM products WHERE slug = 'angel-shirt'), 'Green Text / XXL', 3000, 8),
((SELECT id FROM products WHERE slug = 'what-lies-ahead-of-me'), 'CD', 1200, 25),
((SELECT id FROM products WHERE slug = 'what-lies-ahead-of-me'), '12" Vinyl / Pink', 2400, 15),
((SELECT id FROM products WHERE slug = 'what-lies-ahead-of-me'), '12" Vinyl / Black', 2400, 15),
((SELECT id FROM products WHERE slug = 'collider'), '12" Black Vinyl', 2200, 15),
((SELECT id FROM products WHERE slug = 'auh-cleveland-2026-05-03'), 'GA', 2500, 200),
((SELECT id FROM products WHERE slug = 'auh-nashville-2026-05-05'), 'GA', 2500, 200),
((SELECT id FROM products WHERE slug = 'auh-atlanta-2026-05-07'), 'GA', 2500, 200),
((SELECT id FROM products WHERE slug = 'auh-asheville-2026-05-09'), 'GA', 2500, 200),
((SELECT id FROM products WHERE slug = 'auh-carrboro-2026-05-10'), 'GA', 2500, 200),
((SELECT id FROM products WHERE slug = 'auh-nyc-2026-05-12'), 'GA', 2500, 200),
((SELECT id FROM products WHERE slug = 'auh-cambridge-2026-05-13'), 'GA', 2500, 200),
((SELECT id FROM products WHERE slug = 'auh-hamden-2026-05-14'), 'GA', 2500, 200),
((SELECT id FROM products WHERE slug = 'auh-washington-dc-2026-05-15'), 'GA', 2500, 200),
((SELECT id FROM products WHERE slug = 'auh-allentown-2026-05-16'), 'GA', 2500, 200),
((SELECT id FROM products WHERE slug = 'auh-philadelphia-2026-05-17'), 'GA', 2500, 200),
((SELECT id FROM products WHERE slug = 'auh-detroit-2026-05-19'), 'GA', 2500, 200),
((SELECT id FROM products WHERE slug = 'auh-toronto-2026-05-20'), 'GA', 2500, 200);

INSERT INTO product_images (product_id, variant_id, image_path, alt_text, sort_order, is_primary, is_active) VALUES
((SELECT id FROM products WHERE slug = 'dsa-alley-cat'), NULL, '/images/DSA-AC-Vinyl.webp', 'DSA / Alley Cat black vinyl', 0, 1, 1),
((SELECT id FROM products WHERE slug = 'dsa-alley-cat'), (SELECT pv.id FROM product_variants pv JOIN products p ON p.id = pv.product_id WHERE p.slug = 'dsa-alley-cat' AND pv.name = 'Cassette'), '/images/DSA-AC-Cassette.webp', 'DSA / Alley Cat cassette', 1, 0, 1),
((SELECT id FROM products WHERE slug = 'dsa-alley-cat'), (SELECT pv.id FROM product_variants pv JOIN products p ON p.id = pv.product_id WHERE p.slug = 'dsa-alley-cat' AND pv.name = 'Black Vinyl'), '/images/DSA-AC-Vinyl.webp', 'DSA / Alley Cat black vinyl', 2, 0, 1),
((SELECT id FROM products WHERE slug = 'angel-shirt'), NULL, '/images/AngelsBlackText-store.png', 'Angel Shirt with black text', 0, 1, 1),
((SELECT id FROM products WHERE slug = 'angel-shirt'), (SELECT pv.id FROM product_variants pv JOIN products p ON p.id = pv.product_id WHERE p.slug = 'angel-shirt' AND pv.name = 'Black Text / S'), '/images/AngelsBlackText-store.png', 'Angel Shirt with black text', 1, 0, 1),
((SELECT id FROM products WHERE slug = 'angel-shirt'), (SELECT pv.id FROM product_variants pv JOIN products p ON p.id = pv.product_id WHERE p.slug = 'angel-shirt' AND pv.name = 'Black Text / M'), '/images/AngelsBlackText-store.png', 'Angel Shirt with black text', 2, 0, 1),
((SELECT id FROM products WHERE slug = 'angel-shirt'), (SELECT pv.id FROM product_variants pv JOIN products p ON p.id = pv.product_id WHERE p.slug = 'angel-shirt' AND pv.name = 'Black Text / L'), '/images/AngelsBlackText-store.png', 'Angel Shirt with black text', 3, 0, 1),
((SELECT id FROM products WHERE slug = 'angel-shirt'), (SELECT pv.id FROM product_variants pv JOIN products p ON p.id = pv.product_id WHERE p.slug = 'angel-shirt' AND pv.name = 'Black Text / XL'), '/images/AngelsBlackText-store.png', 'Angel Shirt with black text', 4, 0, 1),
((SELECT id FROM products WHERE slug = 'angel-shirt'), (SELECT pv.id FROM product_variants pv JOIN products p ON p.id = pv.product_id WHERE p.slug = 'angel-shirt' AND pv.name = 'Black Text / XXL'), '/images/AngelsBlackText-store.png', 'Angel Shirt with black text', 5, 0, 1),
((SELECT id FROM products WHERE slug = 'angel-shirt'), (SELECT pv.id FROM product_variants pv JOIN products p ON p.id = pv.product_id WHERE p.slug = 'angel-shirt' AND pv.name = 'Green Text / S'), '/images/AngelsGreenText-store.png', 'Angel Shirt with green text', 6, 0, 1),
((SELECT id FROM products WHERE slug = 'angel-shirt'), (SELECT pv.id FROM product_variants pv JOIN products p ON p.id = pv.product_id WHERE p.slug = 'angel-shirt' AND pv.name = 'Green Text / M'), '/images/AngelsGreenText-store.png', 'Angel Shirt with green text', 7, 0, 1),
((SELECT id FROM products WHERE slug = 'angel-shirt'), (SELECT pv.id FROM product_variants pv JOIN products p ON p.id = pv.product_id WHERE p.slug = 'angel-shirt' AND pv.name = 'Green Text / L'), '/images/AngelsGreenText-store.png', 'Angel Shirt with green text', 8, 0, 1),
((SELECT id FROM products WHERE slug = 'angel-shirt'), (SELECT pv.id FROM product_variants pv JOIN products p ON p.id = pv.product_id WHERE p.slug = 'angel-shirt' AND pv.name = 'Green Text / XL'), '/images/AngelsGreenText-store.png', 'Angel Shirt with green text', 9, 0, 1),
((SELECT id FROM products WHERE slug = 'angel-shirt'), (SELECT pv.id FROM product_variants pv JOIN products p ON p.id = pv.product_id WHERE p.slug = 'angel-shirt' AND pv.name = 'Green Text / XXL'), '/images/AngelsGreenText-store.png', 'Angel Shirt with green text', 10, 0, 1),
((SELECT id FROM products WHERE slug = 'what-lies-ahead-of-me'), NULL, '/images/WLAOMBlackVinyl.webp', 'What Lies Ahead of Me black vinyl', 0, 1, 1),
((SELECT id FROM products WHERE slug = 'what-lies-ahead-of-me'), (SELECT pv.id FROM product_variants pv JOIN products p ON p.id = pv.product_id WHERE p.slug = 'what-lies-ahead-of-me' AND pv.name = 'CD'), '/images/WLAOMCD.webp', 'What Lies Ahead of Me CD', 1, 0, 1),
((SELECT id FROM products WHERE slug = 'what-lies-ahead-of-me'), (SELECT pv.id FROM product_variants pv JOIN products p ON p.id = pv.product_id WHERE p.slug = 'what-lies-ahead-of-me' AND pv.name = '12" Vinyl / Pink'), '/images/WLAOMPinkVinyl.webp', 'What Lies Ahead of Me pink vinyl', 2, 0, 1),
((SELECT id FROM products WHERE slug = 'what-lies-ahead-of-me'), (SELECT pv.id FROM product_variants pv JOIN products p ON p.id = pv.product_id WHERE p.slug = 'what-lies-ahead-of-me' AND pv.name = '12" Vinyl / Black'), '/images/WLAOMBlackVinyl.webp', 'What Lies Ahead of Me black vinyl', 3, 0, 1),
((SELECT id FROM products WHERE slug = 'collider'), NULL, '/images/ColliderBlackVinyl.webp', 'Collider black vinyl', 0, 1, 1),
((SELECT id FROM products WHERE slug = 'collider'), (SELECT pv.id FROM product_variants pv JOIN products p ON p.id = pv.product_id WHERE p.slug = 'collider' AND pv.name = '12" Black Vinyl'), '/images/ColliderBlackVinyl.webp', 'Collider black vinyl', 1, 0, 1);

INSERT INTO ticket_details (product_id, event_date, venue_name, venue_city, venue_state, ticket_mode, external_url, is_on_sale) VALUES
((SELECT id FROM products WHERE slug = 'auh-cleveland-2026-05-03'), '2026-05-03 20:00:00', 'Grog Shop', 'Cleveland', 'OH', 'internal', NULL, 1),
((SELECT id FROM products WHERE slug = 'auh-nashville-2026-05-05'), '2026-05-05 20:00:00', 'Basement East', 'Nashville', 'TN', 'internal', NULL, 1),
((SELECT id FROM products WHERE slug = 'auh-atlanta-2026-05-07'), '2026-05-07 20:00:00', 'Masquerade', 'Atlanta', 'GA', 'internal', NULL, 1),
((SELECT id FROM products WHERE slug = 'auh-asheville-2026-05-09'), '2026-05-09 20:00:00', 'Eulogy', 'Asheville', 'NC', 'internal', NULL, 1),
((SELECT id FROM products WHERE slug = 'auh-carrboro-2026-05-10'), '2026-05-10 20:00:00', 'Cat''s Cradle', 'Carrboro', 'NC', 'internal', NULL, 1),
((SELECT id FROM products WHERE slug = 'auh-nyc-2026-05-12'), '2026-05-12 20:00:00', 'Le Poisson Rouge', 'NYC', 'NY', 'internal', NULL, 1),
((SELECT id FROM products WHERE slug = 'auh-cambridge-2026-05-13'), '2026-05-13 20:00:00', 'The Sinclair', 'Cambridge', 'MA', 'internal', NULL, 1),
((SELECT id FROM products WHERE slug = 'auh-hamden-2026-05-14'), '2026-05-14 20:00:00', 'Space Ballroom', 'Hamden', 'CT', 'internal', NULL, 1),
((SELECT id FROM products WHERE slug = 'auh-washington-dc-2026-05-15'), '2026-05-15 20:00:00', 'Union Stage', 'Washington', 'DC', 'internal', NULL, 1),
((SELECT id FROM products WHERE slug = 'auh-allentown-2026-05-16'), '2026-05-16 20:00:00', 'Arrow', 'Allentown', 'PA', 'internal', NULL, 1),
((SELECT id FROM products WHERE slug = 'auh-philadelphia-2026-05-17'), '2026-05-17 20:00:00', 'Underground Arts', 'Philadelphia', 'PA', 'internal', NULL, 1),
((SELECT id FROM products WHERE slug = 'auh-detroit-2026-05-19'), '2026-05-19 20:00:00', 'The Shelter', 'Detroit', 'MI', 'internal', NULL, 1),
((SELECT id FROM products WHERE slug = 'auh-toronto-2026-05-20'), '2026-05-20 20:00:00', 'The Opera House', 'Toronto', 'ON', 'internal', NULL, 1);
